# Generated by Django 5.1.6 on 2025-03-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course'),
        ),
        migrations.AddField(
            model_name='materialcompletion',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='courses.coursematerial'),
        ),
        migrations.AddField(
            model_name='materialcompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='TeacherNotification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materialcompletion',
            unique_together={('student', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('course', 'student')},
        ),
    ]
